spring:
  application:
    name: harbor-server

  profiles:
    active: local

  main:
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。

  # Servlet 配置
  servlet:
    # 文件上传相关配置项
    multipart:
      max-file-size: 16MB # 单个文件大小
      max-request-size: 32MB # 设置总上传的文件大小
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER # 解决 SpringFox 与 SpringBoot 2.6.x 不兼容的问题，参见 SpringFoxHandlerProviderBeanPostProcessor 类
  #    throw-exception-if-no-handler-found: true # 404 错误时抛出异常，方便统一处理
  #    static-path-pattern: /static/** # 静态资源路径; 注意：如果不配置，则 throw-exception-if-no-handler-found 不生效！！！ TODO 芋艿：不能配置，会导致 swagger 不生效

  # Jackson 配置项
  jackson:
    serialization:
      write-dates-as-timestamps: true # 设置 Date 的格式，使用时间戳
      write-date-timestamps-as-nanoseconds: false # 设置不使用 nanoseconds 的格式。例如说 1611460870.401，而是直接 1611460870401
      write-durations-as-timestamps: true # 设置 Duration 的格式，使用时间戳
      fail-on-empty-beans: false # 允许序列化无属性的 Bean

  # Cache 配置项
  cache:
    type: REDIS
    redis:
      time-to-live: 1h # 设置过期时间为 1 小时

--- #################### 接口文档配置 ####################

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui

knife4j:
  enable: true
  setting:
    language: zh_cn


# MyBatis Plus 的配置项
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  type-aliases-package: ${harbor.info.base-package}.module.*.dal.dataobject
  encryptor:
    password: XDV71a+xqStEA3WH # 加解密的秘钥，可使用 https://www.imaegoo.com/2020/aes-key-generator/ 网站生成

--- #################### 芋道相关配置 ####################

harbor:
  info:
    version: 1.0.0
    base-package: cn.hh.harbor
  web:
    admin-ui:
      url: http://dashboard.harbor.iocoder.cn # Admin 管理后台 UI 的地址
  websocket:
    enable: true # websocket的开关
    path: /websocket/message # 路径
    maxOnlineCount: 0 # 最大连接人数
    sessionMap: true # 保存sessionMap
  swagger:
    title: 反馈港快速开发平台
    description: 提供管理后台、用户 App 的所有功能
    version: ${harbor.info.version}
    url: ${harbor.web.admin-ui.url}
    email: xingyu4j@vip.qq.com
    license: MIT
    license-url: https://gitee.com/zhijiantianya/ruoyi-vue-pro/blob/master/LICENSE
  captcha:
    enable: true # 验证码的开关，默认为 true
  codegen:
    base-package: ${harbor.info.base-package}
    db-schemas: ${spring.datasource.dynamic.datasource.master.name}
    front-type: 10 # 前端模版的类型，参见 CodegenFrontTypeEnum 枚举类
  mq:
    redis:
      pubsub:
        enable: true # 是否开启 Redis pubsub 广播消费，默认为 true。这里设置成 false，可以按需开启
      stream:
        enable: true  # 是否开启 Redis stream 集群消费，默认为 true。这里设置成 false，可以按需开启
  tenant: # 多租户相关配置项
    ignore-urls:
      - /admin-api/system/tenant/**
      - /admin-api/system/select-tenant/** # 租户选择界面
      - /admin-api/system/dict-data/** # 字典和，和租户无关
      - /admin-api/system/auth/** # 用户登录，和租户无关
      - /admin-api/system/captcha/get # 获取图片验证码，和租户无关
      - /admin-api/system/captcha/check # 校验图片验证码，和租户无关
      - /admin-api/infra/file/** # 文件，和租户无关
      - /admin-api/system/sms/callback/** # 短信回调接口，无法带上租户编号
      - /admin-api/system/invite/**
      - /app-api/system/auth/**
    ignore-tables:
      - system_users
      - system_tenant
      - system_tenant_user
      - system_tenant_package
      - system_token_refresh
      - system_token_access
      - system_dict_data
      - system_dict_type
      - system_menu
      - system_sensitive_word
      - system_mail_account
      - system_mail_template
      - system_mail_captcha
      - system_mail_log
      - system_notify_template
      - system_invite_mail
      - system_invite_link
      - system_invite_user
      - infra_codegen_column
      - infra_codegen_table
      - infra_config
      - infra_file_config
      - infra_file
      - infra_file_content
      - infra_job
      - infra_job_log
      - infra_data_source_config
      - harbor_like
  mail-captcha: # 邮箱验证码相关的配置项
    expire-times: 10m
    send-frequency: 1m
    send-maximum-quantity-per-day: 10
    begin-code: 100000
    end-code: 999999
  mail-link-expire-time: 7d # 邮箱链接失效时长
  token-access-time: 1d # 访问令牌有效时长
  token-refresh-time: 25d # 刷新令牌有效时长
debug: false
